name: Test MKMI and Kernel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: compiler
      run: make compiler
    - name: make_mkmi
      run: make -C mkmi static
    - name: make_kernel
      run: make -C microk-kernel kernel
